codecov:
  require_ci_to_pass: yes
  
coverage:
  precision: 2
  round: down
  range: "80...100"

ignore:
  - ".github/workflows"  # ignore folders and all its contents
  - "app/src/test/java/UML"
  - "app/src/main/java/UML/view"
  - "app/src/main/java/UML/controller"
  - "app/src/main/java/UML/App.java"
  
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
